In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
df=pd.read_csv("1.1- Confusion Matrix (Span Mail  Detector) DataSet/emails.csv")

In [3]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [8]:
df.isnull().sum()

text    0
spam    0
dtype: int64

### Separate x and y

In [9]:
x=df.text.values

In [10]:
y=df.spam.values

### Split Dataset

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_trian,y_test=train_test_split(x,y,test_size=0.2)

### Data Preprocessing

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
#object create
cv=CountVectorizer()

In [15]:
res=cv.fit_transform(x_train)

In [16]:
res.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### ML Algorithm

In [17]:
from sklearn.naive_bayes import MultinomialNB

In [18]:
model=MultinomialNB()

In [19]:
model.fit(res,y_trian)

MultinomialNB()

In [20]:
xtest=cv.transform(x_test)

In [21]:
xtest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
model.score(xtest,y_test)

0.9929762949956101

In [23]:
emails = ['hey i am lokking for machine learning tutorial in begali language','hey you win an iphone x giveaway for free please do the survey']

In [24]:
cv_emails=cv.transform(emails)

In [25]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

### Performance

In [26]:
pred=model.predict(xtest)

In [27]:
pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test,pred)

0.9929762949956101

### Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y_test,pred)

array([[865,   7],
       [  1, 266]], dtype=int64)

### TP=844,FP=9,FN=8,TN=278

### CLASSIFICATION

In [32]:
from sklearn.metrics import classification_report

In [33]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       872
           1       0.97      1.00      0.99       267

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

